name: Python package
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: List files for debugging
      run: |
        ls -R
        ls -la
        ls -la bomnal.py
    - name: Run Python scripts
      run: |
        # python bomnal.py
        # python aplus.py
        # python backya.py
        # python better.py
        # python dongne.py
        # python dotori.py
        python lchayim.py
    - name: Commit and Push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "wlsakf23@gmail.com"
        git config --global user.name "kimyih"
        # git add bomnal/bomnal_*.json
        # git add aplus/aplus_*.json
        # git add backya/backya_*.json
        # git add better/better_*.json
        # git add dongne/dongne_*.json
        # git add dotori/dotori_*.json
        git add lchayim/lchayim_*.json

        
        git commit -m "차트 수집 완료"
        git push origin main
